spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demoSpring
    username: root
    password: PHW#84#jeor
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
